"""initial full schema (§8 contract)

Revision ID: 360d34eb8086
Revises: 
Create Date: 2026-06-10 15:20:52.818457
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '360d34eb8086'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector powers the GL-account embedding column (mapping engine, Phase 1).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('deals',
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('property_type', sa.Enum('rv_resort', 'campground', 'glamping', 'cabin_resort', 'marina', 'mobile_home', 'hybrid', name='property_type'), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.Column('site_count', sa.Integer(), nullable=True),
    sa.Column('ask_price', sa.Numeric(), nullable=True),
    sa.Column('price_per_site', sa.Numeric(), nullable=True),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('current_phase', sa.Enum('initial_uw', 'loi', 'contract', 'due_diligence', 'close', name='current_phase'), nullable=False),
    sa.Column('status', sa.Enum('active', 'failed', 'on_ice', 'closed', name='deal_status'), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('gate_questions',
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('phase', sa.Enum('initial_uw', 'loi', 'contract', 'due_diligence', 'close', name='gate_question_phase'), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('default_route_type', sa.Enum('internal', 'external', name='route_type'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('gl_accounts',
    sa.Column('account_code', sa.String(), nullable=False),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('level', sa.Enum('section', 'major_group', 'subgroup', 'leaf', name='account_level'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('normal_balance', sa.String(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('default_noi_placement', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['parent_code'], ['gl_accounts.account_code'], ),
    sa.PrimaryKeyConstraint('account_code')
    )
    op.create_table('question_suggestions',
    sa.Column('suggestion_id', sa.String(), nullable=False),
    sa.Column('phase', sa.Enum('initial_uw', 'loi', 'contract', 'due_diligence', 'close', name='suggestion_phase'), nullable=False),
    sa.Column('type', sa.Enum('add', 'retire', 'edit', name='suggestion_type'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('suggested_by', sa.String(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='suggestion_status'), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    op.create_table('amenities',
    sa.Column('amenity_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('amenity_id')
    )
    op.create_table('assumptions',
    sa.Column('assumption_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('baseline_value', sa.Numeric(), nullable=True),
    sa.Column('shield_source', sa.String(), nullable=True),
    sa.Column('override_value', sa.Numeric(), nullable=True),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('overridden_by', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('assumption_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('unit_type', sa.Enum('rv_pull_through', 'rv_back_in', 'cabin', 'park_model', 'tent', 'glamping', 'marina_slip', 'rv_storage', name='booking_unit_type'), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('gross_revenue', sa.Numeric(), nullable=True),
    sa.Column('adr', sa.Numeric(), nullable=True),
    sa.Column('channel', sa.Enum('direct', 'ota', 'phone', 'walk_in', 'membership', name='channel'), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('comps',
    sa.Column('comp_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.Column('distance_mi', sa.Numeric(), nullable=True),
    sa.Column('avg_rate', sa.Numeric(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('amenity_rank', sa.Integer(), nullable=True),
    sa.Column('amenity_score', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('best_snippet', sa.Text(), nullable=True),
    sa.Column('worst_snippet', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('comp_id')
    )
    op.create_table('deal_gate_items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'requested', 'received', 'accepted', 'waived', 'failed', name='gate_item_status'), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('route_type', sa.Enum('internal', 'external', name='gate_route_type'), nullable=True),
    sa.Column('routed_to', sa.String(), nullable=True),
    sa.Column('date_requested', sa.Date(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('acceptable', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['gate_questions.question_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('deal_photos',
    sa.Column('photo_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('website', 'google', 'seller', 'manual', name='photo_source'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('review_snippet', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('feedback_items',
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('feature', 'bug', 'question', name='feedback_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'triaged', 'needs_detail', 'ready', 'dispatched', 'in_progress', 'deployed', 'closed', 'declined', name='feedback_status'), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('page_route', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('viewport', sa.String(), nullable=True),
    sa.Column('console_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('breadcrumbs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_api_error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('financial_periods',
    sa.Column('period_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('granularity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('period_id')
    )
    op.create_table('gl_mappings_learned',
    sa.Column('mapping_id', sa.String(), nullable=False),
    sa.Column('seller_phrase', sa.Text(), nullable=False),
    sa.Column('source_seller', sa.String(), nullable=True),
    sa.Column('account_code', sa.String(), nullable=False),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_code'], ['gl_accounts.account_code'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_table('hurdles',
    sa.Column('hurdle_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('default_threshold', sa.Numeric(), nullable=True),
    sa.Column('deal_threshold', sa.Numeric(), nullable=True),
    sa.Column('actual_value', sa.Numeric(), nullable=True),
    sa.Column('passes', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('hurdle_id')
    )
    op.create_table('proforma_results',
    sa.Column('result_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('yr', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('opex', sa.Numeric(), nullable=True),
    sa.Column('noi', sa.Numeric(), nullable=True),
    sa.Column('debt_service', sa.Numeric(), nullable=True),
    sa.Column('capex', sa.Numeric(), nullable=True),
    sa.Column('levered_cf', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('proforma_summary',
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('levered_irr', sa.Numeric(), nullable=True),
    sa.Column('equity_multiple', sa.Numeric(), nullable=True),
    sa.Column('equity_basis', sa.Numeric(), nullable=True),
    sa.Column('exit_year', sa.Integer(), nullable=True),
    sa.Column('exit_cap', sa.Numeric(), nullable=True),
    sa.Column('exit_gross_value', sa.Numeric(), nullable=True),
    sa.Column('exit_net_proceeds', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('units',
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('unit_type', sa.Enum('rv_pull_through', 'rv_back_in', 'cabin', 'park_model', 'tent', 'glamping', 'marina_slip', 'rv_storage', name='unit_type'), nullable=False),
    sa.Column('hookup_level', sa.Enum('full', 'water_electric', 'partial', 'dry', 'na', name='hookup_level'), nullable=True),
    sa.Column('amp_rating', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('occupancy_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('waterfall_tiers',
    sa.Column('tier_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('irr_floor', sa.Numeric(), nullable=True),
    sa.Column('irr_ceiling', sa.Numeric(), nullable=True),
    sa.Column('lp_split', sa.Numeric(), nullable=True),
    sa.Column('gp_split', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('tier_id')
    )
    op.create_table('weekly_summary',
    sa.Column('summary_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('available_unit_nights', sa.Integer(), nullable=True),
    sa.Column('occupied_unit_nights', sa.Integer(), nullable=True),
    sa.Column('occupancy_pct', sa.Numeric(), nullable=True),
    sa.Column('adr', sa.Numeric(), nullable=True),
    sa.Column('revpau', sa.Numeric(), nullable=True),
    sa.Column('gross_revenue', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Enum('computed', 'seller_provided', name='weekly_summary_source'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_table('feedback_attachments',
    sa.Column('attachment_id', sa.String(), nullable=False),
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_items.feedback_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('feedback_comments',
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_items.feedback_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('feedback_dispatch',
    sa.Column('dispatch_id', sa.String(), nullable=False),
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('github_issue_url', sa.String(), nullable=True),
    sa.Column('github_pr_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dispatched_by', sa.String(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_items.feedback_id'], ),
    sa.PrimaryKeyConstraint('dispatch_id')
    )
    op.create_table('financial_lines',
    sa.Column('line_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('period_id', sa.String(), nullable=False),
    sa.Column('account_code', sa.String(), nullable=True),
    sa.Column('account_level', sa.Enum('section', 'major_group', 'subgroup', 'leaf', name='fl_account_level'), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('seller_source_line', sa.Text(), nullable=True),
    sa.Column('map_confidence', sa.Enum('leaf', 'coarse', 'unmapped', name='map_confidence'), nullable=True),
    sa.Column('map_confidence_score', sa.Numeric(), nullable=True),
    sa.Column('noi_placement', sa.Enum('above', 'below', 'non_operating', name='noi_placement'), nullable=True),
    sa.Column('is_addback', sa.Boolean(), nullable=False),
    sa.Column('addback_amount', sa.Numeric(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_code'], ['gl_accounts.account_code'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.period_id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_lines')
    op.drop_table('feedback_dispatch')
    op.drop_table('feedback_comments')
    op.drop_table('feedback_attachments')
    op.drop_table('weekly_summary')
    op.drop_table('waterfall_tiers')
    op.drop_table('units')
    op.drop_table('proforma_summary')
    op.drop_table('proforma_results')
    op.drop_table('hurdles')
    op.drop_table('gl_mappings_learned')
    op.drop_table('financial_periods')
    op.drop_table('feedback_items')
    op.drop_table('deal_photos')
    op.drop_table('deal_gate_items')
    op.drop_table('comps')
    op.drop_table('bookings')
    op.drop_table('assumptions')
    op.drop_table('amenities')
    op.drop_table('question_suggestions')
    op.drop_table('gl_accounts')
    op.drop_table('gate_questions')
    op.drop_table('deals')
    # Drop the named ENUM types the tables created (Postgres keeps them otherwise),
    # so a downgrade→upgrade cycle is clean.
    op.execute('DROP TYPE IF EXISTS account_level')
    op.execute('DROP TYPE IF EXISTS booking_unit_type')
    op.execute('DROP TYPE IF EXISTS channel')
    op.execute('DROP TYPE IF EXISTS current_phase')
    op.execute('DROP TYPE IF EXISTS deal_status')
    op.execute('DROP TYPE IF EXISTS feedback_status')
    op.execute('DROP TYPE IF EXISTS feedback_type')
    op.execute('DROP TYPE IF EXISTS fl_account_level')
    op.execute('DROP TYPE IF EXISTS gate_item_status')
    op.execute('DROP TYPE IF EXISTS gate_question_phase')
    op.execute('DROP TYPE IF EXISTS gate_route_type')
    op.execute('DROP TYPE IF EXISTS hookup_level')
    op.execute('DROP TYPE IF EXISTS map_confidence')
    op.execute('DROP TYPE IF EXISTS noi_placement')
    op.execute('DROP TYPE IF EXISTS photo_source')
    op.execute('DROP TYPE IF EXISTS property_type')
    op.execute('DROP TYPE IF EXISTS route_type')
    op.execute('DROP TYPE IF EXISTS suggestion_phase')
    op.execute('DROP TYPE IF EXISTS suggestion_status')
    op.execute('DROP TYPE IF EXISTS suggestion_type')
    op.execute('DROP TYPE IF EXISTS unit_type')
    op.execute('DROP TYPE IF EXISTS weekly_summary_source')
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###
