"""add population_rings (market sizing)

Revision ID: 6f81cfee1ece
Revises: 360d34eb8086
Create Date: 2026-06-11 03:13:05.071213
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6f81cfee1ece'
down_revision: str | None = '360d34eb8086'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_rings',
    sa.Column('ring_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('radius_mi', sa.Integer(), nullable=False),
    sa.Column('baseline_population', sa.Integer(), nullable=True),
    sa.Column('override_population', sa.Integer(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('overridden_by', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('ring_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population_rings')
    # ### end Alembic commands ###
