"""GL chart seed — the full RJourney chart of accounts (design doc §8.5, decision §14 B-13).

Generated from the consolidated income statement's chart-of-accounts column (structure only — no
dollar amounts). Each row: (account_code, parent_code, level, name, section, normal_balance, sort,
default_noi_placement). ``default_noi_placement`` travels with the account so 700000 lines are
treated below the line and 800000/900000/950000 as non-operating during normalization.

Two source codes are reused for different accounts (600400, 600410); the second of each is stored
with a ``-2`` suffix here (so ``account_code`` stays a unique key) and should be recoded at source.

The consolidated views are NOT a complete superset — some accounts appear only on per-park sheets
(e.g. 600145 Payroll Processing Fees, 605840 Wells One Credit Card). Those are unioned in (see the
"Park-only accounts" block) so no deal can carry a line that doesn't map. ``CONTRA_CODES`` /
``CORE_CODES`` below are applied at seed time to set ``gl_accounts.is_contra`` / ``tier``.
Re-generate from the workbook rather than hand-editing. See DECISIONS.md (canonical GL chart).
"""

from __future__ import annotations

from typing import TypedDict


class GLRow(TypedDict):
    account_code: str
    parent_code: str | None
    level: str
    name: str
    section: str
    normal_balance: str
    sort: int
    default_noi_placement: str


GL_ACCOUNTS: list[GLRow] = [
    {
        "account_code": "400000",
        "parent_code": None,
        "level": "major_group",
        "name": "Revenue",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 10,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400100",
        "parent_code": "400000",
        "level": "subgroup",
        "name": "Campground Rent",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 20,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400105",
        "parent_code": "400100",
        "level": "leaf",
        "name": "RV Short Term",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 30,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400110",
        "parent_code": "400100",
        "level": "leaf",
        "name": "RV Extended Stay",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 40,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400115",
        "parent_code": "400100",
        "level": "leaf",
        "name": "Lodging Short Term",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 50,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400120",
        "parent_code": "400100",
        "level": "leaf",
        "name": "Tent",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 60,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400125",
        "parent_code": "400100",
        "level": "leaf",
        "name": "Pavilion / Clubhouse Rental",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 70,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400130",
        "parent_code": "400100",
        "level": "leaf",
        "name": "Parking",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 80,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400135",
        "parent_code": "400100",
        "level": "leaf",
        "name": "Sign Rental",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 90,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400140",
        "parent_code": "400100",
        "level": "leaf",
        "name": "Uncategorized Rent",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 100,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400145",
        "parent_code": "400100",
        "level": "leaf",
        "name": "Rent Refunds",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 110,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400200",
        "parent_code": "400000",
        "level": "subgroup",
        "name": "Self Storage Rent",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 120,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400210",
        "parent_code": "400200",
        "level": "leaf",
        "name": "Self Storage",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 130,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400220",
        "parent_code": "400200",
        "level": "leaf",
        "name": "Retail Space",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 140,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400300",
        "parent_code": "400000",
        "level": "subgroup",
        "name": "Housing Rental",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 150,
        "default_noi_placement": "above",
    },
    {
        "account_code": "400310",
        "parent_code": "400300",
        "level": "leaf",
        "name": "Residential House Rental",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 160,
        "default_noi_placement": "above",
    },
    {
        "account_code": "401000",
        "parent_code": "400000",
        "level": "subgroup",
        "name": "Online Travel Agencies",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 170,
        "default_noi_placement": "above",
    },
    {
        "account_code": "401010",
        "parent_code": "401000",
        "level": "leaf",
        "name": "OTA - RV Short Term",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 180,
        "default_noi_placement": "above",
    },
    {
        "account_code": "401070",
        "parent_code": "401000",
        "level": "leaf",
        "name": "OTA - Commissions Expense (Contra)",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 190,
        "default_noi_placement": "above",
    },
    {
        "account_code": "401200",
        "parent_code": "401000",
        "level": "leaf",
        "name": "OTA Notional Clearing",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 200,
        "default_noi_placement": "above",
    },
    {
        "account_code": "402000",
        "parent_code": "400000",
        "level": "subgroup",
        "name": "Marina Revenue",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 210,
        "default_noi_placement": "above",
    },
    {
        "account_code": "402010",
        "parent_code": "402000",
        "level": "leaf",
        "name": "Marina Slip Rental",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 220,
        "default_noi_placement": "above",
    },
    {
        "account_code": "402070",
        "parent_code": "402000",
        "level": "leaf",
        "name": "Other Marina Revenue",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 230,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403000",
        "parent_code": "400000",
        "level": "subgroup",
        "name": "Ancillary Revenue",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 240,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403005",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Booking Fees",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 250,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403010",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Admin Fees",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 260,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403020",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Cancellations Penalties",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 270,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403030",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Credit Card & ACH Convenience Fees",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 280,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403040",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Golf Cart Rental",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 290,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403050",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Housekeeping / Cleaning Service",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 300,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403060",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Late Fee",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 310,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403070",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Protection Plan",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 320,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403080",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Rental Addons",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 330,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403090",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Utility Metering Fees",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 340,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403100",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Vendor Commission",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 350,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403110",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Vending Machines",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 360,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403120",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Water & Sanitation Services",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 370,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403140",
        "parent_code": "403000",
        "level": "leaf",
        "name": "General",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 380,
        "default_noi_placement": "above",
    },
    {
        "account_code": "404000",
        "parent_code": "400000",
        "level": "subgroup",
        "name": "Retail Sales",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 390,
        "default_noi_placement": "above",
    },
    {
        "account_code": "404010",
        "parent_code": "404000",
        "level": "leaf",
        "name": "Campstore - PMS",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 400,
        "default_noi_placement": "above",
    },
    {
        "account_code": "404020",
        "parent_code": "404000",
        "level": "leaf",
        "name": "Campstore - POS",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 410,
        "default_noi_placement": "above",
    },
    {
        "account_code": "404040",
        "parent_code": "404000",
        "level": "leaf",
        "name": "Propane Refill/Resale",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 420,
        "default_noi_placement": "above",
    },
    {
        "account_code": "404060",
        "parent_code": "404000",
        "level": "leaf",
        "name": "Uncategorized",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 430,
        "default_noi_placement": "above",
    },
    {
        "account_code": "404070",
        "parent_code": "404000",
        "level": "leaf",
        "name": "POS Discounts & Allowances",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 440,
        "default_noi_placement": "above",
    },
    {
        "account_code": "420000",
        "parent_code": "400000",
        "level": "subgroup",
        "name": "Discounts & Allowances",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 450,
        "default_noi_placement": "above",
    },
    {
        "account_code": "421000",
        "parent_code": "420000",
        "level": "leaf",
        "name": "Discounts",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 460,
        "default_noi_placement": "above",
    },
    {
        "account_code": "421300",
        "parent_code": "420000",
        "level": "leaf",
        "name": "Work Camper Campsite Credit",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 470,
        "default_noi_placement": "above",
    },
    {
        "account_code": "421400",
        "parent_code": "420000",
        "level": "leaf",
        "name": "Maintenance Opportunity Loss",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 480,
        "default_noi_placement": "above",
    },
    {
        "account_code": "430000",
        "parent_code": None,
        "level": "leaf",
        "name": "Earned Unbilled Services",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 490,
        "default_noi_placement": "above",
    },
    {
        "account_code": "500000",
        "parent_code": None,
        "level": "major_group",
        "name": "Cost of Goods Sold",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 500,
        "default_noi_placement": "above",
    },
    {
        "account_code": "500200",
        "parent_code": "500000",
        "level": "leaf",
        "name": "COGS - Campstore",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 510,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600100",
        "parent_code": None,
        "level": "major_group",
        "name": "Wages & Compensation",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 520,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600130",
        "parent_code": "600100",
        "level": "leaf",
        "name": "Employee Health Benefits",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 530,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600140",
        "parent_code": "600100",
        "level": "leaf",
        "name": "Payroll Expenses",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 540,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600155",
        "parent_code": "600100",
        "level": "leaf",
        "name": "Payroll Tax Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 550,
        "default_noi_placement": "above",
    },
    # Defaults-engine home (additive): a BUDGETED payroll allocation ($85/employee/mo) kept
    # distinct from actual wages (600140) — it accrues and is not actually charged.
    {
        "account_code": "600145",
        "parent_code": "600100",
        "level": "leaf",
        "name": "Payroll Budget Allocation",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 545,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600200",
        "parent_code": None,
        "level": "major_group",
        "name": "Advertising & Promotion",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 560,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600210",
        "parent_code": "600200",
        "level": "leaf",
        "name": "Website Maintenance & Hosting",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 570,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600215",
        "parent_code": "600200",
        "level": "leaf",
        "name": "Print Media & Signage",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 580,
        "default_noi_placement": "above",
    },
    # Defaults-engine home (additive): the call-center / reservations answering service ($750/mo).
    {
        "account_code": "600220",
        "parent_code": "600200",
        "level": "leaf",
        "name": "Call Center",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 585,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600225",
        "parent_code": "600200",
        "level": "leaf",
        "name": "Pay-Per-Click",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 590,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600230",
        "parent_code": "600200",
        "level": "subgroup",
        "name": "Event Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 600,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600245",
        "parent_code": "600230",
        "level": "leaf",
        "name": "Decor & Supplies",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 610,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600250",
        "parent_code": "600230",
        "level": "leaf",
        "name": "Entertainment",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 620,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600255",
        "parent_code": "600230",
        "level": "leaf",
        "name": "Food & Beverage",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 630,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600240",
        "parent_code": "600200",
        "level": "leaf",
        "name": "Promotions",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 640,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600235",
        "parent_code": None,
        "level": "leaf",
        "name": "Commission Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 650,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600400",
        "parent_code": None,
        "level": "major_group",
        "name": "Office Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 660,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600405",
        "parent_code": "600400",
        "level": "leaf",
        "name": "Office Supplies",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 670,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600410",
        "parent_code": "600400",
        "level": "leaf",
        "name": "Office Software Support",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 680,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600415",
        "parent_code": "600400",
        "level": "leaf",
        "name": "Postage",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 690,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600420",
        "parent_code": "600400",
        "level": "leaf",
        "name": "Contributions",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 700,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600430",
        "parent_code": "600400",
        "level": "leaf",
        "name": "Miscellaneous",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 710,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600435",
        "parent_code": "600400",
        "level": "leaf",
        "name": "Cash Over & Short",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 720,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600400-2",
        "parent_code": None,
        "level": "major_group",
        "name": "Sales & Marketing Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 730,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600410-2",
        "parent_code": "600400-2",
        "level": "leaf",
        "name": "Travel & Automotive",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 740,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600500",
        "parent_code": None,
        "level": "major_group",
        "name": "Dues & Subscriptions",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 750,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600355",
        "parent_code": "600500",
        "level": "leaf",
        "name": "Campground Memberships",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 760,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600600",
        "parent_code": None,
        "level": "major_group",
        "name": "Software & Technology Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 770,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600615",
        "parent_code": "600600",
        "level": "leaf",
        "name": "AI Database Services",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 780,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600620",
        "parent_code": "600600",
        "level": "leaf",
        "name": "Business Productivity Suite",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 790,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600625",
        "parent_code": "600600",
        "level": "leaf",
        "name": "General Database Services",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 800,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600630",
        "parent_code": "600600",
        "level": "leaf",
        "name": "Payment Processing Services",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 810,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600700",
        "parent_code": None,
        "level": "leaf",
        "name": "Credit Card Processing Fees",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 820,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600900",
        "parent_code": None,
        "level": "major_group",
        "name": "Permits & Business Licenses",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 830,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600905",
        "parent_code": "600900",
        "level": "leaf",
        "name": "License Bus. Taxes, Permits",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 840,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600910",
        "parent_code": "600900",
        "level": "leaf",
        "name": "Alcohol/Liquor License",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 850,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600915",
        "parent_code": "600900",
        "level": "leaf",
        "name": "Music & Movie Licenses",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 860,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600920",
        "parent_code": "600900",
        "level": "leaf",
        "name": "Annual Reports & Renewals",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 870,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600925",
        "parent_code": "600900",
        "level": "leaf",
        "name": "Formations & Registrations",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 880,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601000",
        "parent_code": None,
        "level": "major_group",
        "name": "Consulting Services",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 890,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601010",
        "parent_code": "601000",
        "level": "leaf",
        "name": "Marketing Service",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 900,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601100",
        "parent_code": None,
        "level": "major_group",
        "name": "Bad Debt",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 910,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601105",
        "parent_code": "601100",
        "level": "leaf",
        "name": "Bad Debt Recovery",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 920,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601200",
        "parent_code": None,
        "level": "major_group",
        "name": "Finance Fees",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 930,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601205",
        "parent_code": "601200",
        "level": "leaf",
        "name": "Analysis",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 940,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601215",
        "parent_code": "601200",
        "level": "leaf",
        "name": "Vendor Late Fees",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 950,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601220",
        "parent_code": "601200",
        "level": "leaf",
        "name": "NSF Fee",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 960,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601235",
        "parent_code": "601200",
        "level": "leaf",
        "name": "Service Charge",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 970,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601300",
        "parent_code": None,
        "level": "leaf",
        "name": "Sales Tax Expense Adjustments",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 980,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605000",
        "parent_code": None,
        "level": "major_group",
        "name": "Operations & Maintenance",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 990,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605100",
        "parent_code": "605000",
        "level": "subgroup",
        "name": "Repairs & Maintenance",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1000,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605105",
        "parent_code": "605100",
        "level": "leaf",
        "name": "Building Materials",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1010,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605110",
        "parent_code": "605100",
        "level": "leaf",
        "name": "Repair Contractor Services",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1020,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605115",
        "parent_code": "605100",
        "level": "leaf",
        "name": "Repair Parts & Supplies",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1030,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605120",
        "parent_code": "605100",
        "level": "leaf",
        "name": "Small Tools",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1040,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605125",
        "parent_code": "605100",
        "level": "leaf",
        "name": "Maintenance & Landscape Fuel",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1050,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605130",
        "parent_code": "605100",
        "level": "leaf",
        "name": "Marina Maintenance",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1060,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605200",
        "parent_code": "605000",
        "level": "subgroup",
        "name": "Housekeeping",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1070,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605205",
        "parent_code": "605200",
        "level": "leaf",
        "name": "Cleaning Supplies",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1080,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605210",
        "parent_code": "605200",
        "level": "leaf",
        "name": "Furniture & Appliance",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1090,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605215",
        "parent_code": "605200",
        "level": "leaf",
        "name": "Linen & Services",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1100,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605300",
        "parent_code": "605000",
        "level": "subgroup",
        "name": "Pool Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1110,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605305",
        "parent_code": "605300",
        "level": "leaf",
        "name": "Pool Contracted Labor",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1120,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605310",
        "parent_code": "605300",
        "level": "leaf",
        "name": "Chemicals & Treatments",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1130,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605315",
        "parent_code": "605300",
        "level": "leaf",
        "name": "Pool Parts & Supplies",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1140,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605320",
        "parent_code": "605300",
        "level": "leaf",
        "name": "Pool Testing Supplies",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1150,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605820",
        "parent_code": "605300",
        "level": "leaf",
        "name": "Games & Activities",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1160,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605400",
        "parent_code": "605000",
        "level": "subgroup",
        "name": "Utilities",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1170,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605405",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Disposal",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1180,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605410",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Electric",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1190,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605415",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Utility Recovery",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1200,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605420",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Natural Gas",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1210,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605425",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Propane Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1220,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605430",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Internet",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1230,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605435",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Satelite",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1240,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605440",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Telephone",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1250,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605445",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Cell Phone",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1260,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605450",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Water-Well Testing & Permits",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1270,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605455",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Water & Sewer",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1280,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605460",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Septic Pumping & Treatment",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1290,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605465",
        "parent_code": "605400",
        "level": "leaf",
        "name": "Water & Sewer Recovery",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1300,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605500",
        "parent_code": "605000",
        "level": "subgroup",
        "name": "Landscaping",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1310,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605505",
        "parent_code": "605500",
        "level": "leaf",
        "name": "Landscaping Contractor",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1320,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605510",
        "parent_code": "605500",
        "level": "leaf",
        "name": "Pest Control",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1330,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605515",
        "parent_code": "605500",
        "level": "leaf",
        "name": "Pond Maintenance",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1340,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605520",
        "parent_code": "605500",
        "level": "leaf",
        "name": "Landscaping Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1350,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605525",
        "parent_code": "605500",
        "level": "leaf",
        "name": "Mulching & Sod Repair",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1360,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605530",
        "parent_code": "605500",
        "level": "leaf",
        "name": "Planting Trees & Flowers",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1370,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605535",
        "parent_code": "605500",
        "level": "leaf",
        "name": "Spraying (Fert. & Weed Killer)",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1380,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605540",
        "parent_code": "605500",
        "level": "leaf",
        "name": "Tree Trimming",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1390,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605600",
        "parent_code": "605000",
        "level": "leaf",
        "name": "Security & Survaliance",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1400,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605605",
        "parent_code": "605000",
        "level": "leaf",
        "name": "Gates",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1410,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605700",
        "parent_code": "605000",
        "level": "leaf",
        "name": "Freight & Transportation",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1420,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605800",
        "parent_code": "605000",
        "level": "subgroup",
        "name": "Rental & Lease",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1430,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605810",
        "parent_code": "605800",
        "level": "leaf",
        "name": "Equipment Rental",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1440,
        "default_noi_placement": "above",
    },
    {
        "account_code": "605815",
        "parent_code": "605000",
        "level": "leaf",
        "name": "Auction Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1450,
        "default_noi_placement": "above",
    },
    {
        "account_code": "607000",
        "parent_code": None,
        "level": "leaf",
        "name": "Property Tax Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1460,
        "default_noi_placement": "above",
    },
    {
        "account_code": "607100",
        "parent_code": None,
        "level": "major_group",
        "name": "Insurance Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1470,
        "default_noi_placement": "above",
    },
    {
        "account_code": "607105",
        "parent_code": "607100",
        "level": "leaf",
        "name": "Auto/Bond/Prop/Casualty",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1480,
        "default_noi_placement": "above",
    },
    {
        "account_code": "700000",
        "parent_code": None,
        "level": "major_group",
        "name": "Debt Service Interest",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1490,
        "default_noi_placement": "below",
    },
    {
        "account_code": "704000",
        "parent_code": "700000",
        "level": "leaf",
        "name": "Regular Interest",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1500,
        "default_noi_placement": "below",
    },
    {
        "account_code": "800000",
        "parent_code": None,
        "level": "major_group",
        "name": "Non-Operational Expenses",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1510,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "605545",
        "parent_code": "800000",
        "level": "leaf",
        "name": "Landscaping",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1520,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800020",
        "parent_code": "800000",
        "level": "leaf",
        "name": "Legal Fees",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1530,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800030",
        "parent_code": "800000",
        "level": "leaf",
        "name": "Professional Services",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1540,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800040",
        "parent_code": "800000",
        "level": "leaf",
        "name": "CapEx Allocation - Repairs",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1550,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800045",
        "parent_code": "800000",
        "level": "leaf",
        "name": "CapEx Allocation - Equip Purchases",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1560,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800050",
        "parent_code": "800000",
        "level": "leaf",
        "name": "CapEx Allocation - Payroll",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1570,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800060",
        "parent_code": "800000",
        "level": "leaf",
        "name": "Travel & Automotive Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1580,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800070",
        "parent_code": "800000",
        "level": "leaf",
        "name": "Meals & Entertainment",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1590,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800080",
        "parent_code": "800000",
        "level": "leaf",
        "name": "Automotive Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1600,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800090",
        "parent_code": "800000",
        "level": "leaf",
        "name": "Travel Fuel",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1610,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "800100",
        "parent_code": "800000",
        "level": "leaf",
        "name": "Automotive Travel Fuel",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1620,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "900000",
        "parent_code": None,
        "level": "major_group",
        "name": "Other Income",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 1630,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "900010",
        "parent_code": "900000",
        "level": "leaf",
        "name": "Prior Year Revenue",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 1640,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "901500",
        "parent_code": "900000",
        "level": "leaf",
        "name": "Early Payment Discount",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 1650,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "902000",
        "parent_code": "900000",
        "level": "leaf",
        "name": "Interest Income",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 1660,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "904000",
        "parent_code": "900000",
        "level": "leaf",
        "name": "Gain/(Loss) Sale of Asset",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 1670,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "950000",
        "parent_code": None,
        "level": "major_group",
        "name": "Other Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1680,
        "default_noi_placement": "non_operating",
    },
    {
        "account_code": "952000",
        "parent_code": "950000",
        "level": "leaf",
        "name": "Prior Period Expenses",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1690,
        "default_noi_placement": "non_operating",
    },
    # ── Park-only accounts (present in per-park sheets but absent from the consolidated
    # views). Unioned in so no deal can carry a line that doesn't map. ──────────────────
    {
        "account_code": "605840",
        "parent_code": "605800",
        "level": "leaf",
        "name": "Wells One Credit Card",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1442,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600425",
        "parent_code": "600400",
        "level": "leaf",
        "name": "Employee Uniforms",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 722,
        "default_noi_placement": "above",
    },
    {
        "account_code": "500100",
        "parent_code": "500000",
        "level": "leaf",
        "name": "COGS - Propane Refill",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 512,
        "default_noi_placement": "above",
    },
    {
        "account_code": "601210",
        "parent_code": "601200",
        "level": "leaf",
        "name": "Bank Error",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 972,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600105",
        "parent_code": "600100",
        "level": "leaf",
        "name": "Administrative",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 552,
        "default_noi_placement": "above",
    },
    {
        "account_code": "607110",
        "parent_code": "607100",
        "level": "leaf",
        "name": "Tenant Insurance Claims Expense",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 1482,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600135",
        "parent_code": "600100",
        "level": "leaf",
        "name": "Health Insurance",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 552,
        "default_noi_placement": "above",
    },
    {
        "account_code": "403130",
        "parent_code": "403000",
        "level": "leaf",
        "name": "Wifi Revenue",
        "section": "Income",
        "normal_balance": "credit",
        "sort": 382,
        "default_noi_placement": "above",
    },
    {
        "account_code": "600115",
        "parent_code": "600100",
        "level": "leaf",
        "name": "Training Mgmt",
        "section": "Expense",
        "normal_balance": "debit",
        "sort": 552,
        "default_noi_placement": "above",
    },
]


# ── Canonical-chart metadata, applied to gl_accounts at seed time (keyed on the BASE code, i.e.
# the part before any ``-2`` disambiguation suffix). Derived from the 31-sheet income statement;
# see DECISIONS.md (canonical GL chart).
CONTRA_CODES = frozenset(  # sign-preserving negative offsets (recoveries / discounts / credits)
    {
        "401070",
        "404070",
        "421000",
        "421300",
        "421400",
        "605415",
        "605465",
    }
)


CORE_CODES = (
    frozenset(  # leaves present in >=60% (16/27) of the portfolio's parks; the rest are 'rare'
        {
            "400105",
            "400110",
            "400115",
            "400130",
            "400310",
            "401070",
            "401200",
            "403005",
            "403010",
            "403020",
            "403030",
            "403060",
            "403080",
            "403090",
            "403110",
            "403140",
            "404010",
            "404020",
            "404070",
            "421000",
            "421300",
            "421400",
            "500200",
            "600130",
            "600140",
            "600145",
            "600155",
            "600210",
            "600215",
            "600225",
            "600235",
            "600245",
            "600250",
            "600255",
            "600405",
            "600415",
            "600430",
            "600700",
            "600905",
            "600915",
            "600920",
            "601215",
            "601235",
            "601300",
            "605105",
            "605110",
            "605115",
            "605120",
            "605125",
            "605205",
            "605210",
            "605215",
            "605310",
            "605315",
            "605405",
            "605410",
            "605415",
            "605425",
            "605430",
            "605440",
            "605445",
            "605455",
            "605465",
            "605510",
            "605520",
            "605535",
            "607000",
            "607105",
        }
    )
)
